### ISSUE TITLE
Ternoa Phase 3 Feature List

### ISSUE THREAD

**Issue by markopoloparadox** [capsule-corp-ternoa/ternoa-hub#19]
Here I will list all the features that we need to do (and the person who is in charge) in order to finish phase 3.

### Blockchain Team

- [x] Node and Substrate Upgrade - @markopoloparadox  - [![Generic badge](https://img.shields.io/badge/Status-Confirmed-white.svg)](https://shields.io/) [![Generic badge](https://img.shields.io/badge/Status-InQA-yellow.svg)](https://shields.io/) - https://github.com/capsule-corp-ternoa/chain/issues/264
- [x] Renting NFTs - @Leouarz - [![Generic badge](https://img.shields.io/badge/Status-Confirmed-white.svg)](https://shields.io/) [![Generic badge](https://img.shields.io/badge/Status-InQA-yellow.svg)](https://shields.io/) - https://github.com/capsule-corp-ternoa/chain/issues/227
- [x] Auction NFTs - @Leouarz - [![Generic badge](https://img.shields.io/badge/Status-Confirmed-white.svg)](https://shields.io/) [![Generic badge](https://img.shields.io/badge/Status-InQA-yellow.svg)](https://shields.io/) - https://github.com/capsule-corp-ternoa/chain/issues/229
- [x] Custom Tokens (Assets) - @markopoloparadox  - [![Generic badge](https://img.shields.io/badge/Status-Confirmed-white.svg)](https://shields.io/) [![Generic badge](https://img.shields.io/badge/Status-InQA-yellow.svg)](https://shields.io/) - https://github.com/capsule-corp-ternoa/chain/issues/263
- [x] Soulbound NFT v2 - @Leouarz - [![Generic badge](https://img.shields.io/badge/Status-Confirmed-white.svg)](https://shields.io/) [![Generic badge](https://img.shields.io/badge/Status-InQA-yellow.svg)](https://shields.io/) - https://github.com/capsule-corp-ternoa/chain/issues/262
- [x] Update readme file and add docker/podman support - @markopoloparadox  - [![Generic badge](https://img.shields.io/badge/Status-Confirmed-white.svg)](https://shields.io/) [![Generic badge](https://img.shields.io/badge/Status-Done-green.svg)](https://shields.io/) - https://github.com/capsule-corp-ternoa/chain/issues/255

### Offchain Team

- [x] Auction NFTs pallet SDK - @ipapandinas - [![Generic badge](https://img.shields.io/badge/Status-Confirmed-white.svg)](https://shields.io/) [![Generic badge](https://img.shields.io/badge/Status-InBacklog-red.svg)](https://shields.io/) - https://github.com/capsule-corp-ternoa/ternoa-js/issues/83
- [x] Renting NFTs pallet SDK - @Victor-Salomon - [![Generic badge](https://img.shields.io/badge/Status-Confirmed-white.svg)](https://shields.io/) [![Generic badge](https://img.shields.io/badge/Status-InBacklog-red.svg)](https://shields.io/) - https://github.com/capsule-corp-ternoa/ternoa-js/issues/84
- [x] Auction NFTs pallet Indexer - @ipapandinas - [![Generic badge](https://img.shields.io/badge/Status-Confirmed-white.svg)](https://shields.io/) [![Generic badge](https://img.shields.io/badge/Status-InBacklog-red.svg)](https://shields.io/) - https://github.com/capsule-corp-ternoa/ternoa-subql/issues/106
- [x] Renting NFTs pallet Indexer - @Victor-Salomon - [![Generic badge](https://img.shields.io/badge/Status-Confirmed-white.svg)](https://shields.io/) [![Generic badge](https://img.shields.io/badge/Status-InBacklog-red.svg)](https://shields.io/) - https://github.com/capsule-corp-ternoa/ternoa-subql/issues/107
